// Research phrase lists for the Match Finder, grouped "Group: Subcategory".
window.EXTRA_PHRASES = {
 "Ancient: Babylon And Mesopotamia": [
  "Babylon",
  "Fall of Babylon",
  "Babylon the Great",
  "Mystery Babylon",
  "Babylon Is Fallen",
  "Rivers of Babylon",
  "Whore of Babylon",
  "Marduk",
  "Marduk King of Babylon",
  "Marduk the Dragon Slayer",
  "Ishtar",
  "Ishtar Queen of Heaven",
  "Gate of Ishtar",
  "The Ishtar Gate",
  "Tammuz",
  "Weeping for Tammuz",
  "Tower of Babel",
  "The Tower of Babel",
  "Confusion of Tongues",
  "Nimrod",
  "Nimrod the Mighty Hunter",
  "Nebuchadnezzar",
  "King Nebuchadnezzar",
  "Nebuchadnezzar King of Babylon",
  "Belshazzar",
  "Writing on the Wall",
  "Mene Mene Tekel Upharsin",
  "Ziggurat",
  "Ziggurat of Ur",
  "The Great Ziggurat",
  "Ur of the Chaldees",
  "The Chaldeans",
  "Hanging Gardens",
  "Hanging Gardens of Babylon",
  "Hammurabi",
  "Code of Hammurabi",
  "Sumer",
  "Akkad",
  "Sargon of Akkad",
  "Gilgamesh",
  "Epic of Gilgamesh",
  "Anunnaki",
  "The Anunnaki",
  "Nineveh",
  "Assyria",
  "Mesopotamia",
  "Tigris and Euphrates"
 ],
 "Ancient: Egypt": [
  "Egypt",
  "Ancient Egypt",
  "Land of Egypt",
  "Out of Egypt",
  "Ra",
  "Ra the Sun God",
  "Amun Ra",
  "Eye of Ra",
  "Osiris",
  "Osiris Lord of the Dead",
  "Isis",
  "Isis Queen of Heaven",
  "Horus",
  "Eye of Horus",
  "Set",
  "Set the Destroyer",
  "Seth God of Chaos",
  "Anubis",
  "Anubis Guardian of the Dead",
  "Thoth",
  "Sekhmet",
  "Apophis",
  "Pharaoh",
  "The Pharaoh",
  "Pharaoh of Egypt",
  "Tutankhamun",
  "King Tut",
  "Ramses the Great",
  "Cleopatra",
  "Pyramids of Giza",
  "The Great Pyramid",
  "Great Pyramid of Giza",
  "The Sphinx",
  "Great Sphinx of Giza",
  "Valley of the Kings",
  "Thebes",
  "Alexandria",
  "Library of Alexandria",
  "Nile River",
  "Book of the Dead",
  "Ten Plagues of Egypt"
 ],
 "Ancient: Canaanite And Phoenician": [
  "Baal",
  "Baal Hadad",
  "Prophets of Baal",
  "Worship of Baal",
  "Baal Zebub",
  "Beelzebub",
  "Lord of the Flies",
  "Molech",
  "Moloch",
  "Fires of Molech",
  "Asherah",
  "Asherah Poles",
  "Astarte",
  "Ashtoreth",
  "Queen of Heaven",
  "Dagon",
  "Temple of Dagon",
  "Chemosh",
  "Canaan",
  "Land of Canaan",
  "The Canaanites",
  "Phoenicia",
  "The Phoenicians",
  "Tyre",
  "Prince of Tyre",
  "King of Tyre",
  "Sidon",
  "Tyre and Sidon",
  "Carthage",
  "Carthage Must Be Destroyed",
  "Hannibal",
  "Tophet",
  "Valley of Hinnom",
  "Gehenna",
  "Jezebel"
 ],
 "Ancient: Greece": [
  "Zeus",
  "Zeus King of the Gods",
  "Poseidon",
  "Hades",
  "Hades Lord of the Underworld",
  "Apollo",
  "Apollo the Sun God",
  "Athena",
  "Ares God of War",
  "Aphrodite",
  "Hermes",
  "Dionysus",
  "Persephone",
  "Kronos",
  "The Titans",
  "Prometheus",
  "Olympus",
  "Mount Olympus",
  "Gods of Olympus",
  "Delphi",
  "Oracle of Delphi",
  "Parthenon",
  "Acropolis",
  "Sparta",
  "Troy",
  "Fall of Troy",
  "Trojan Horse",
  "Hercules",
  "Medusa",
  "Pandoras Box",
  "Alexander the Great",
  "River Styx",
  "Tartarus",
  "Underworld",
  "Colossus of Rhodes",
  "Seat of Satan"
 ],
 "Ancient: Rome": [
  "Rome",
  "Ancient Rome",
  "Roman Empire",
  "The Roman Empire",
  "Fall of Rome",
  "Rome Is Burning",
  "All Roads Lead to Rome",
  "Eternal City",
  "City of Seven Hills",
  "Seven Hills of Rome",
  "Jupiter",
  "Mars",
  "Mars God of War",
  "Saturn",
  "Venus",
  "Vestal Virgins",
  "Sol Invictus",
  "Mithras",
  "Caesar",
  "Julius Caesar",
  "Hail Caesar",
  "Render unto Caesar",
  "Augustus",
  "Caesar Augustus",
  "Caligula",
  "Nero",
  "Emperor Nero",
  "Nero Caesar",
  "Constantine",
  "Colosseum",
  "The Colosseum",
  "Pantheon",
  "Circus Maximus",
  "Roman Legion",
  "Pax Romana",
  "Pompeii",
  "Mount Vesuvius",
  "Ides of March"
 ],
 "Ancient: Norse": [
  "Odin",
  "Odin the Allfather",
  "Allfather",
  "Thor",
  "Thor God of Thunder",
  "Mjolnir",
  "Loki",
  "Loki the Trickster",
  "Freya",
  "Heimdall",
  "Hel",
  "Fenrir",
  "Ragnarok",
  "Twilight of the Gods",
  "Valhalla",
  "Hall of the Slain",
  "Valkyries",
  "Asgard",
  "Yggdrasil",
  "World Tree",
  "Norse Gods"
 ],
 "Ancient: Persia India And Americas": [
  "Persia",
  "Persian Empire",
  "Ahura Mazda",
  "Ahriman",
  "Zoroaster",
  "Mithra",
  "Persepolis",
  "Cyrus",
  "Cyrus the Great",
  "Darius",
  "Xerxes",
  "Medes and Persians",
  "Magi",
  "Shiva",
  "Shiva the Destroyer",
  "Lord Shiva",
  "Vishnu",
  "Vishnu the Preserver",
  "Brahma",
  "Brahma the Creator",
  "Kali",
  "Kali the Dark Mother",
  "Kali Yuga",
  "Krishna",
  "Kurukshetra",
  "Battle of Kurukshetra",
  "Bhagavad Gita",
  "Mahabharata",
  "Quetzalcoatl",
  "Feathered Serpent",
  "The Feathered Serpent",
  "Teotihuacan",
  "City of the Gods",
  "Pyramid of the Sun",
  "Aztec Empire",
  "Mayan Calendar",
  "Chichen Itza"
 ],
 "Ancient: Legends And Monuments": [
  "Stonehenge",
  "Druids",
  "Atlantis",
  "Lost City of Atlantis",
  "Fall of Atlantis",
  "Sinking of Atlantis",
  "Plato and Atlantis",
  "Seven Wonders",
  "Seven Wonders of the Ancient World",
  "Gobekli Tepe",
  "Great Flood",
  "Nephilim",
  "Giants in the Earth",
  "Ancient Aliens"
 ],
 "Ancient: Biblical Places": [
  "Sodom and Gomorrah",
  "Sodom",
  "Gomorrah",
  "Fire and Brimstone",
  "Pillar of Salt",
  "Mount Sinai",
  "Ten Commandments",
  "Mount Horeb",
  "Burning Bush",
  "Jericho",
  "Walls of Jericho",
  "Fall of Jericho",
  "Jonah and Nineveh",
  "Megiddo",
  "Armageddon",
  "Battle of Armageddon",
  "Valley of Megiddo",
  "Golgotha",
  "Place of the Skull",
  "Calvary",
  "Mount of Olives",
  "Garden of Gethsemane",
  "Gethsemane",
  "Mount Zion",
  "Zion",
  "Jerusalem",
  "Temple Mount",
  "Mount Moriah",
  "Solomons Temple",
  "Mount Ararat",
  "Noahs Ark",
  "Garden of Eden",
  "Bethlehem",
  "Nazareth",
  "Sea of Galilee",
  "Jordan River",
  "Red Sea",
  "Parting of the Red Sea",
  "Dead Sea",
  "Patmos",
  "Promised Land"
 ],
 "Atomic: Manhattan Project": [
  "Manhattan Project",
  "The Manhattan Project",
  "Project Y",
  "Site Y",
  "Los Alamos",
  "Los Alamos Laboratory",
  "Los Alamos National Laboratory",
  "Oak Ridge",
  "Oak Ridge Tennessee",
  "Hanford Site",
  "Hanford Washington",
  "Hanford Reactor",
  "B Reactor",
  "Y Twelve Plant",
  "K Twenty Five",
  "Calutron",
  "Chicago Pile One",
  "Enrico Fermi",
  "First Chain Reaction",
  "Robert Oppenheimer",
  "J Robert Oppenheimer",
  "General Leslie Groves",
  "Leslie Groves",
  "Edward Teller",
  "Niels Bohr",
  "Hans Bethe",
  "Richard Feynman",
  "Leo Szilard",
  "Einstein Szilard Letter",
  "Albert Einstein",
  "Klaus Fuchs",
  "Atomic Spies",
  "Army Corps of Engineers",
  "Manhattan Engineer District",
  "The Gadget",
  "Implosion Design",
  "Gun Type Design",
  "Plutonium Two Thirty Nine",
  "Uranium Two Thirty Five",
  "Enriched Uranium",
  "Weapons Grade Plutonium",
  "Secret City",
  "The Hill",
  "Fuller Lodge",
  "Box One Six Six Three",
  "Bradbury Science Museum"
 ],
 "Atomic: Trinity Test": [
  "Trinity",
  "Trinity Test",
  "The Trinity Test",
  "Trinity Site",
  "Jornada del Muerto",
  "Journey of the Dead Man",
  "White Sands",
  "White Sands Missile Range",
  "Alamogordo",
  "Alamogordo Bombing Range",
  "July Sixteen Nineteen Forty Five",
  "Sixteenth of July",
  "Five Twenty Nine AM",
  "Ground Zero",
  "Trinitite",
  "Jumbo",
  "McDonald Ranch House",
  "The First Atomic Bomb",
  "First Nuclear Detonation",
  "Dawn of the Atomic Age",
  "The Atomic Age",
  "Kenneth Bainbridge",
  "Now We Are All Sons of Bitches",
  "Batter My Heart Three Person God"
 ],
 "Atomic: Oppenheimer Quote": [
  "Now I Am Become Death",
  "Now I Am Become Death the Destroyer of Worlds",
  "I Am Become Death",
  "The Destroyer of Worlds",
  "Destroyer of Worlds",
  "The Bhagavad Gita",
  "Arjuna",
  "Radiance of a Thousand Suns",
  "If the Radiance of a Thousand Suns",
  "Brighter Than a Thousand Suns",
  "Father of the Atomic Bomb",
  "American Prometheus",
  "Oppenheimer Security Hearing",
  "Security Clearance Revoked",
  "Enrico Fermi Award"
 ],
 "Atomic: Hiroshima and Nagasaki": [
  "Little Boy",
  "Fat Man",
  "Enola Gay",
  "Bockscar",
  "Paul Tibbets",
  "Charles Sweeney",
  "Tinian Island",
  "Hiroshima",
  "Nagasaki",
  "Hiroshima and Nagasaki",
  "August Six Nineteen Forty Five",
  "August Nine Nineteen Forty Five",
  "Hibakusha",
  "Hiroshima Peace Memorial",
  "Atomic Bomb Dome",
  "Genbaku Dome",
  "Peace Memorial Park",
  "Sadako Sasaki",
  "Thousand Paper Cranes",
  "Urakami Cathedral",
  "Kokura",
  "Aioi Bridge",
  "Nuclear Shadow",
  "Black Rain",
  "Surrender of Japan",
  "Victory Over Japan",
  "End of World War Two",
  "Five Hundred Ninth Composite Group",
  "Harry Truman",
  "Potsdam Declaration"
 ],
 "Atomic: Cold War": [
  "Cold War",
  "The Cold War",
  "Iron Curtain",
  "Arms Race",
  "The Arms Race",
  "Nuclear Arms Race",
  "Doomsday Clock",
  "The Doomsday Clock",
  "Ninety Seconds to Midnight",
  "Eighty Nine Seconds to Midnight",
  "Bulletin of the Atomic Scientists",
  "Mutually Assured Destruction",
  "Mutual Assured Destruction",
  "Nuclear Deterrence",
  "Cuban Missile Crisis",
  "Thirteen Days",
  "Bay of Pigs",
  "Berlin Wall",
  "Duck and Cover",
  "Fallout Shelter",
  "Red Scare",
  "Sputnik",
  "Space Race",
  "The Space Race",
  "Tsar Bomba",
  "The Tsar Bomba",
  "Fifty Megatons",
  "Novaya Zemlya",
  "Castle Bravo",
  "Bikini Atoll",
  "Enewetak Atoll",
  "Marshall Islands",
  "Operation Crossroads",
  "Ivy Mike",
  "Lucky Dragon",
  "Semipalatinsk",
  "Joe One",
  "First Lightning",
  "Hydrogen Bomb",
  "The Hydrogen Bomb",
  "Thermonuclear Weapon",
  "Teller Ulam Design",
  "Strategic Air Command",
  "Minuteman Missile",
  "Intercontinental Ballistic Missile",
  "Nuclear Triad",
  "Red Telephone",
  "Star Wars Program",
  "Strategic Defense Initiative",
  "Limited Test Ban Treaty",
  "Nuclear Non Proliferation Treaty",
  "SALT Treaty",
  "Able Archer",
  "Stanislav Petrov",
  "The Man Who Saved the World",
  "Fall of the Berlin Wall",
  "Soviet Union",
  "Kremlin",
  "Pentagon",
  "NORAD",
  "Cheyenne Mountain",
  "Dead Hand"
 ],
 "Atomic: Rocketry and Space": [
  "Jet Propulsion Laboratory",
  "The Jet Propulsion Laboratory",
  "JPL",
  "JPL Pasadena",
  "Pasadena",
  "Pasadena California",
  "Arroyo Seco",
  "Arroyo Seco Rocket Tests",
  "Suicide Squad",
  "Caltech",
  "Theodore von Karman",
  "Frank Malina",
  "Jack Parsons",
  "John Whiteside Parsons",
  "Explorer One",
  "Operation Paperclip",
  "Project Paperclip",
  "Wernher von Braun",
  "Von Braun",
  "Peenemunde",
  "V Two Rocket",
  "Redstone Arsenal",
  "Huntsville Alabama",
  "Rocket City",
  "Saturn Five",
  "NASA",
  "The NASA",
  "National Aeronautics and Space Administration",
  "Apollo Program",
  "Apollo Eleven",
  "Apollo One",
  "Apollo Thirteen",
  "Neil Armstrong",
  "Buzz Aldrin",
  "Michael Collins",
  "One Small Step",
  "The Eagle Has Landed",
  "Tranquility Base",
  "Sea of Tranquility",
  "Houston We Have a Problem",
  "Mission Control",
  "Kennedy Space Center",
  "Cape Canaveral",
  "Project Mercury",
  "Project Gemini",
  "Space Shuttle",
  "Challenger",
  "Columbia",
  "Yuri Gagarin",
  "Vostok One",
  "Baikonur Cosmodrome",
  "Voyager Golden Record",
  "Voyager One",
  "Deep Space Network",
  "Mars Rover"
 ],
 "Atomic: New Mexico and Nevada": [
  "New Mexico",
  "Land of Enchantment",
  "Santa Fe",
  "Albuquerque",
  "Sandia",
  "Sandia National Laboratories",
  "Kirtland Air Force Base",
  "Socorro",
  "Carrizozo",
  "San Antonio New Mexico",
  "Bingham",
  "Tularosa Basin",
  "Holloman Air Force Base",
  "Roswell",
  "Roswell New Mexico",
  "The Roswell Incident",
  "Roswell UFO Incident",
  "Project Mogul",
  "Nineteen Forty Seven",
  "Waste Isolation Pilot Plant",
  "Carlsbad",
  "Very Large Array",
  "Pajarito Plateau",
  "Jemez Mountains",
  "Bandelier",
  "Nevada",
  "Nevada Test Site",
  "Nevada National Security Site",
  "Yucca Flat",
  "Frenchman Flat",
  "Mercury Nevada",
  "Yucca Mountain",
  "Las Vegas",
  "Atomic Tourism",
  "Mushroom Cloud",
  "Area Fifty One",
  "Area Five One",
  "Groom Lake",
  "Dreamland",
  "Rachel Nevada",
  "Extraterrestrial Highway",
  "Nellis Air Force Base",
  "Nellis Range",
  "Tonopah",
  "Downwinders",
  "Saint George Utah",
  "Operation Plumbbob",
  "Operation Upshot Knothole",
  "Sedan Crater",
  "Project Plowshare"
 ],
 "Atomic: Reactors and Disasters": [
  "Chernobyl",
  "Chernobyl Disaster",
  "Chernobyl Nuclear Power Plant",
  "Reactor Number Four",
  "April Twenty Six Nineteen Eighty Six",
  "Pripyat",
  "Exclusion Zone",
  "The Zone of Alienation",
  "Elephants Foot",
  "Red Forest",
  "The Sarcophagus",
  "New Safe Confinement",
  "Liquidators",
  "Fukushima",
  "Fukushima Daiichi",
  "Fukushima Disaster",
  "Tohoku Earthquake",
  "Great East Japan Earthquake",
  "Tsunami",
  "March Eleven Twenty Eleven",
  "Three Mile Island",
  "Windscale Fire",
  "Kyshtym Disaster",
  "Mayak",
  "SL One",
  "Nuclear Meltdown",
  "Core Meltdown",
  "China Syndrome",
  "Nuclear Accident",
  "Level Seven Event",
  "Radioactive Fallout",
  "Nuclear Winter"
 ],
 "Atomic: CERN and Physics": [
  "CERN",
  "The CERN",
  "European Organization for Nuclear Research",
  "Large Hadron Collider",
  "The Large Hadron Collider",
  "LHC",
  "Geneva Switzerland",
  "Meyrin",
  "Franco Swiss Border",
  "Higgs Boson",
  "The God Particle",
  "Peter Higgs",
  "Standard Model",
  "ATLAS Detector",
  "Compact Muon Solenoid",
  "Particle Accelerator",
  "Particle Collider",
  "Proton Collision",
  "Antimatter",
  "Shiva Statue",
  "Dance of Shiva",
  "Nataraja",
  "World Wide Web",
  "Tim Berners Lee",
  "Fermilab",
  "Brookhaven",
  "Lawrence Livermore",
  "Lawrence Berkeley",
  "Ernest Lawrence",
  "Cyclotron",
  "Marie Curie",
  "Ernest Rutherford",
  "Splitting the Atom",
  "Lise Meitner",
  "Otto Hahn",
  "E Equals MC Squared",
  "Quantum Mechanics"
 ],
 "Atomic: Nuclear Terms": [
  "Nuclear",
  "Atomic Bomb",
  "The Atomic Bomb",
  "Atom Bomb",
  "Nuclear Weapon",
  "Nuclear Bomb",
  "Nuclear Fission",
  "Nuclear Fusion",
  "Chain Reaction",
  "Critical Mass",
  "Supercritical",
  "Neutron",
  "Proton",
  "Electron",
  "Isotope",
  "Uranium",
  "Plutonium",
  "Tritium",
  "Deuterium",
  "Heavy Water",
  "Yellowcake",
  "Centrifuge",
  "Enrichment",
  "Half Life",
  "Radiation",
  "Radioactivity",
  "Gamma Ray",
  "Ionizing Radiation",
  "Geiger Counter",
  "Rad",
  "Sievert",
  "Becquerel",
  "Fallout",
  "Megaton",
  "Kiloton",
  "Fifteen Kilotons",
  "Twenty One Kilotons",
  "Blast Radius",
  "Shock Wave",
  "Fireball",
  "Nuclear Reactor",
  "Control Rods",
  "Fuel Rods",
  "Nuclear Waste",
  "Dirty Bomb",
  "Neutron Bomb",
  "Warhead",
  "Nuclear Holocaust",
  "Nuclear War",
  "Atomic Energy",
  "Atoms for Peace",
  "Atomic Energy Commission",
  "Department of Energy",
  "International Atomic Energy Agency",
  "Demon Core",
  "Harry Daghlian",
  "Louis Slotin",
  "Tickling the Dragons Tail",
  "Broken Arrow",
  "Nuclear Football",
  "Launch Codes",
  "DEFCON One",
  "Big Red Button"
 ],
 "Bible: Revelation Imagery": [
  "The Seven Seals",
  "Seven Seals",
  "The Four Horsemen",
  "Four Horsemen of the Apocalypse",
  "The White Horse",
  "The Red Horse",
  "The Black Horse",
  "The Pale Horse",
  "Rider on the White Horse",
  "The Seven Trumpets",
  "Seven Trumpets",
  "The Seven Bowls",
  "Seven Bowls of Wrath",
  "The Seven Churches",
  "Seven Golden Lampstands",
  "The New Jerusalem",
  "New Heaven and New Earth",
  "The Great White Throne",
  "Great White Throne Judgment",
  "The Mark of the Beast",
  "Mark of the Beast",
  "The Number of the Beast",
  "The Two Witnesses",
  "Two Witnesses",
  "Woman Clothed with the Sun",
  "The Great Red Dragon",
  "The Beast from the Sea",
  "The Beast from the Earth",
  "The False Prophet",
  "The Whore of Babylon",
  "The Mother of Harlots",
  "The Lake of Fire",
  "The Book of Life",
  "The Bottomless Pit"
 ],
 "Bible: Daniel and Prophecy": [
  "The Seventy Weeks",
  "Seventy Weeks of Daniel",
  "The Seventieth Week",
  "Ancient of Days",
  "The Writing on the Wall",
  "Weighed and Found Wanting",
  "The Lions Den",
  "Daniel in the Lions Den",
  "The Fiery Furnace",
  "Shadrach Meshach and Abednego",
  "Belshazzars Feast",
  "The Statue of Four Metals",
  "Head of Gold",
  "Feet of Iron and Clay",
  "The Stone Cut Without Hands",
  "The Four Beasts",
  "The Little Horn",
  "The Ram and the Goat",
  "Time Times and Half a Time",
  "The Time of the End",
  "Seal the Book",
  "The Stump of Jesse",
  "A Virgin Shall Conceive",
  "Unto Us a Child Is Born",
  "The Suffering Servant",
  "By His Stripes We Are Healed"
 ],
 "Bible: Famous Verses": [
  "It Is Finished",
  "I Am the Way",
  "I Am the Way the Truth and the Life",
  "Let There Be Light",
  "In the Beginning",
  "In the Beginning Was the Word",
  "The Word Was God",
  "The Word Became Flesh",
  "I Am the Resurrection",
  "I Am the Light of the World",
  "I Am the Bread of Life",
  "I Am the Good Shepherd",
  "I Am the True Vine",
  "I Am the Door",
  "Before Abraham Was I Am",
  "For God So Loved the World",
  "God Is Love",
  "Jesus Wept",
  "He Is Risen",
  "He Is Not Here",
  "The Lord Is My Shepherd",
  "The Valley of the Shadow of Death",
  "My Cup Runneth Over",
  "Be Still and Know",
  "Father Forgive Them",
  "Into Thy Hands",
  "Eli Eli Lama Sabachthani",
  "My God Why Hast Thou Forsaken Me",
  "Thy Will Be Done",
  "Thy Kingdom Come",
  "Our Father Who Art in Heaven",
  "Give Us This Day",
  "Deliver Us from Evil",
  "Lead Us Not into Temptation",
  "Love Thy Neighbor",
  "Love Your Enemies"
 ],
 "Bible: Patriarchs and Prophets": [
  "Abraham Father of Nations",
  "Father Abraham",
  "Isaac the Promised Son",
  "Jacob Called Israel",
  "Jacob Wrestled the Angel",
  "Jacobs Ladder",
  "Joseph the Dreamer",
  "Coat of Many Colors",
  "Moses the Lawgiver",
  "Moses and the Burning Bush",
  "The Ten Commandments",
  "The Tablets of Stone",
  "Aaron the High Priest",
  "Aarons Rod",
  "Joshua Son of Nun",
  "The Walls of Jericho",
  "Samuel the Seer",
  "King David",
  "David and Goliath",
  "The Sweet Psalmist of Israel",
  "King Solomon",
  "The Wisdom of Solomon",
  "Elijah the Tishbite",
  "Elijah and the Chariot of Fire",
  "The Still Small Voice",
  "Elisha the Prophet",
  "Isaiah the Prophet",
  "Jeremiah the Weeping Prophet",
  "Ezekiel the Watchman",
  "Daniel the Beloved",
  "Jonah and the Whale",
  "Hosea"
 ],
 "Bible: Angels and Heavenly Hosts": [
  "Michael the Archangel",
  "Gabriel the Messenger",
  "Raphael the Healer",
  "Uriel",
  "Seraphim",
  "Cherubim",
  "Thrones",
  "Dominions",
  "Virtues",
  "Powers",
  "Principalities",
  "Archangels",
  "The Nine Choirs of Angels",
  "The Heavenly Host",
  "Hosts of Heaven",
  "The Angel of the Lord",
  "The Angel of Death",
  "The Destroying Angel",
  "Guardian Angel",
  "Angels Unaware",
  "Lucifer",
  "Lucifer Son of the Morning",
  "Satan",
  "The Devil",
  "The Accuser",
  "The Serpent"
 ],
 "Bible: Names of God": [
  "El Elyon",
  "El Shaddai",
  "El Olam",
  "El Roi",
  "El Gibbor",
  "Elohim",
  "Adonai",
  "Yahweh",
  "Jehovah",
  "Jehovah Jireh",
  "Yahweh Nissi",
  "Jehovah Rapha",
  "Jehovah Shalom",
  "Jehovah Shammah",
  "Jehovah Tsidkenu",
  "Jehovah Rohi",
  "Jehovah Sabaoth",
  "Lord of Hosts",
  "I Am That I Am",
  "Ehyeh Asher Ehyeh",
  "The Great I Am",
  "The Tetragrammaton",
  "YHWH",
  "Yeshua",
  "Yeshua Hamashiach",
  "The Holy One of Israel",
  "The Most High",
  "The Almighty"
 ],
 "Bible: Greek and Hebrew Terms": [
  "Logos",
  "The Logos",
  "Agape",
  "Agape Love",
  "Philia",
  "Eros",
  "Storge",
  "Parousia",
  "Maranatha",
  "Ekklesia",
  "Koinonia",
  "Kerygma",
  "Evangelion",
  "Christos",
  "Kyrios",
  "Theos",
  "Pneuma",
  "Charis",
  "Pistis",
  "Metanoia",
  "Soteria",
  "Apokalypsis",
  "Eschaton",
  "Kairos",
  "Chronos",
  "Rhema",
  "Dunamis",
  "Shekinah"
 ],
 "Bible: Church History and Sacraments": [
  "Council of Nicaea",
  "The Nicene Creed",
  "The Apostles Creed",
  "Pentecost",
  "The Day of Pentecost",
  "Tongues of Fire",
  "The Upper Room",
  "The Last Supper",
  "The Lords Supper",
  "Holy Communion",
  "The Eucharist",
  "Holy Baptism",
  "Baptism by Water",
  "Confirmation",
  "Holy Orders",
  "Anointing of the Sick",
  "Confession",
  "Holy Matrimony",
  "The Seven Sacraments",
  "The Reformation",
  "The Protestant Reformation",
  "Martin Luther",
  "The Ninety Five Theses",
  "Sola Fide",
  "Sola Scriptura",
  "Sola Gratia",
  "Solus Christus",
  "Soli Deo Gloria",
  "John Calvin",
  "John Wesley",
  "The Great Awakening",
  "The Council of Trent"
 ],
 "Bible: Saints and Miracles": [
  "Saint Peter",
  "Saint Paul",
  "Saint John",
  "Saint Stephen",
  "Saint Stephen the First Martyr",
  "Saint Augustine",
  "Saint Francis of Assisi",
  "Saint Patrick",
  "Saint Nicholas",
  "Saint Benedict",
  "Saint Thomas Aquinas",
  "Saint Joan of Arc",
  "Saint Jerome",
  "Saint Athanasius",
  "Saint George and the Dragon",
  "Saint Mark",
  "Saint Luke",
  "Saint Matthew",
  "Saint Andrew",
  "Saint James",
  "Saint Jude",
  "Water into Wine",
  "Wedding at Cana",
  "Feeding the Five Thousand",
  "Five Loaves and Two Fish",
  "Walking on Water",
  "Jesus Walks on Water",
  "Calming the Storm"
 ],
 "Bible: Holy Land and Fish": [
  "Galilee",
  "The Sea of Galilee",
  "The River Jordan",
  "The Place of the Skull",
  "Isle of Patmos",
  "Mount Carmel",
  "Mount Tabor",
  "Ichthys",
  "The Ichthys Fish",
  "Jesus Fish",
  "The Sign of the Fish",
  "Fishers of Men",
  "I Will Make You Fishers of Men",
  "One Hundred Fifty Three Fish",
  "The Hundred Fifty Three Fish",
  "The Miraculous Catch",
  "The Miraculous Draught of Fishes",
  "Cast the Net on the Right Side",
  "The Net Was Not Broken",
  "Loaves and Fishes",
  "Two Small Fish",
  "The Coin in the Fish",
  "The Fishermen Disciples",
  "Feed My Sheep",
  "Do You Love Me"
 ],
 "Military: Operations and Codenames": [
  "Operation Overlord",
  "D Day",
  "The D Day Landings",
  "Operation Barbarossa",
  "Operation Desert Storm",
  "Desert Storm",
  "Operation Northwoods",
  "Operation Mockingbird",
  "Operation Market Garden",
  "Operation Torch",
  "Operation Valkyrie",
  "Operation Sea Lion",
  "Operation Fortitude",
  "Operation Mincemeat",
  "Operation Bodyguard",
  "Operation Dynamo",
  "Operation Downfall",
  "Operation Rolling Thunder",
  "Operation Ajax",
  "Operation Gladio",
  "Operation Condor",
  "Operation Mongoose",
  "Operation Iraqi Freedom",
  "Operation Enduring Freedom",
  "Operation Neptune Spear",
  "Operation Entebbe",
  "Operation Wrath of God",
  "Operation Highjump",
  "Operation Ivy Bells",
  "Operation Popeye",
  "Operation Anthropoid",
  "Operation Chastise",
  "Operation Bagration",
  "Operation Citadel",
  "Operation Unthinkable",
  "The Bay of Pigs Invasion",
  "Iran Contra Affair",
  "Gulf of Tonkin Incident",
  "The Doolittle Raid",
  "The Berlin Airlift"
 ],
 "Military: Intelligence Programs": [
  "MKUltra",
  "Project MKUltra",
  "Project Stargate",
  "Remote Viewing",
  "Project Blue Book",
  "Majestic Twelve",
  "COINTELPRO",
  "Counter Intelligence Program",
  "Project Artichoke",
  "Project Bluebird",
  "Project Monarch",
  "Project Grill Flame",
  "Project Sun Streak",
  "Venona Project",
  "Project Azorian",
  "Project Echelon",
  "Project Prism",
  "Project Shamrock",
  "Operation Midnight Climax",
  "Project Acoustic Kitty",
  "Project Iceworm",
  "Project Blue Beam",
  "The Pentagon Papers",
  "The Church Committee",
  "Project Looking Glass",
  "Stay Behind Network"
 ],
 "Military: Agencies and Units": [
  "Central Intelligence Agency",
  "The Central Intelligence Agency",
  "National Security Agency",
  "The National Security Agency",
  "No Such Agency",
  "Defense Intelligence Agency",
  "Defense Advanced Research Projects Agency",
  "DARPA",
  "Office of Strategic Services",
  "Federal Bureau of Investigation",
  "Secret Intelligence Service",
  "MI Six",
  "MI Five",
  "KGB",
  "The KGB",
  "The Stasi",
  "Mossad",
  "The Mossad",
  "Shin Bet",
  "Delta Force",
  "Navy SEALs",
  "SEAL Team Six",
  "Green Berets",
  "Special Air Service",
  "Special Operations Executive",
  "National Reconnaissance Office",
  "Joint Chiefs of Staff",
  "Department of Defense",
  "The French Foreign Legion",
  "The Waffen SS",
  "The Gestapo",
  "The Wehrmacht",
  "The Luftwaffe",
  "The Red Army",
  "Five Eyes",
  "The Deep State",
  "The Military Industrial Complex"
 ],
 "Military: Bases and Places": [
  "The Pentagon",
  "Fort Knox",
  "Langley",
  "Cheyenne Mountain Complex",
  "Pine Gap",
  "Diego Garcia",
  "Dugway Proving Ground",
  "Wright Patterson Air Force Base",
  "Hangar Eighteen",
  "Fort Meade",
  "Fort Bragg",
  "Fort Detrick",
  "Guantanamo Bay",
  "Camp David",
  "Mount Weather",
  "Raven Rock",
  "Menwith Hill",
  "Porton Down",
  "Bletchley Park",
  "The Situation Room",
  "The War Room",
  "The Kremlin",
  "Checkpoint Charlie",
  "The Berlin Wall",
  "The Iron Curtain",
  "The Maginot Line",
  "The Atlantic Wall",
  "The Wolf Lair",
  "The Fuhrerbunker",
  "West Point",
  "Arlington National Cemetery"
 ],
 "Military: Wars and Battles": [
  "Waterloo",
  "The Battle of Waterloo",
  "Gettysburg",
  "The Battle of Gettysburg",
  "Stalingrad",
  "The Battle of Stalingrad",
  "Normandy",
  "The Normandy Landings",
  "Omaha Beach",
  "Iwo Jima",
  "The Battle of Iwo Jima",
  "Pearl Harbor",
  "The Attack on Pearl Harbor",
  "Vietnam",
  "The Vietnam War",
  "The Tet Offensive",
  "Dien Bien Phu",
  "The Crusades",
  "The First Crusade",
  "The Knights Templar",
  "Siege of Jerusalem",
  "The Siege of Jerusalem",
  "Siege of Masada",
  "Masada",
  "Battle of Hastings",
  "Battle of Agincourt",
  "Battle of Thermopylae",
  "The Three Hundred",
  "Battle of Marathon",
  "Battle of Lepanto",
  "Siege of Constantinople",
  "Fall of Constantinople",
  "Battle of Trafalgar",
  "Battle of Austerlitz",
  "Battle of the Somme",
  "Battle of Verdun",
  "Gallipoli",
  "Battle of Midway",
  "Battle of Britain",
  "Battle of the Bulge",
  "Dunkirk",
  "El Alamein",
  "Black Hawk Down",
  "World War One",
  "World War Two",
  "The Korean War",
  "The Gulf War",
  "The Yom Kippur War",
  "The Hundred Years War",
  "The Napoleonic Wars",
  "The Civil War",
  "The American Revolution",
  "The Trojan War",
  "The War on Terror",
  "The Cuban Missile Crisis"
 ],
 "Military: Esoteric Crossover": [
  "Ahnenerbe",
  "The Ahnenerbe",
  "Wewelsburg",
  "Wewelsburg Castle",
  "Thule Society",
  "The Thule Society",
  "Vril Society",
  "The Vril Society",
  "Spear of Destiny",
  "The Spear of Destiny",
  "The Black Sun",
  "The Black Order",
  "Nazi Occultism",
  "Die Glocke",
  "The Nazi Bell",
  "Hollow Earth",
  "Psychic Spies",
  "Psychic Warfare",
  "The Men Who Stare at Goats",
  "The First Earth Battalion",
  "Psyop",
  "Psychological Operations",
  "Psychological Warfare",
  "Mind Control",
  "The Manchurian Candidate",
  "Controlled Remote Viewing",
  "The Montauk Project",
  "The Philadelphia Experiment",
  "Project Rainbow",
  "Foo Fighters",
  "The Babalon Working",
  "Skull and Bones",
  "Bohemian Grove",
  "Numbers Stations"
 ],
 "Military: Weapons and Programs": [
  "Star Wars",
  "Brilliant Pebbles",
  "HAARP",
  "High Frequency Active Auroral Research Program",
  "Project Thor",
  "Project Excalibur",
  "Directed Energy Weapons",
  "The Death Ray",
  "Weather Warfare",
  "Agent Orange",
  "Napalm",
  "Chemical Weapons",
  "The Stealth Bomber",
  "The Blackbird",
  "The Tomahawk",
  "The Patriot Missile",
  "The Trident",
  "The Doomsday Machine",
  "The Nuclear Football",
  "The Red Phone",
  "The Enigma Machine",
  "Ultra Secret",
  "Purple Cipher",
  "Navajo Code Talkers",
  "The Zimmermann Telegram",
  "The Iron Dome",
  "The Stuxnet Worm",
  "The Tiger Tank",
  "The Blitzkrieg",
  "The Spitfire",
  "The Dreadnought",
  "The Trojan Horse",
  "Greek Fire",
  "The Gatling Gun",
  "The Kalashnikov",
  "Project Habakkuk",
  "The Bat Bomb"
 ],
 "Military: Commanders and Spies": [
  "Sun Tzu",
  "The Art of War",
  "Hannibal Barca",
  "Genghis Khan",
  "Napoleon Bonaparte",
  "Duke of Wellington",
  "Joan of Arc",
  "George Patton",
  "Dwight Eisenhower",
  "Douglas MacArthur",
  "Erwin Rommel",
  "The Desert Fox",
  "Lawrence of Arabia",
  "The Red Baron",
  "Wild Bill Donovan",
  "Allen Dulles",
  "J Edgar Hoover",
  "Heinrich Himmler",
  "Mata Hari",
  "Kim Philby",
  "The Cambridge Five",
  "Richard Sorge",
  "Alan Turing",
  "Ace of Spies",
  "Benedict Arnold",
  "Sidney Gottlieb",
  "Ingo Swann",
  "Double Agent",
  "Sleeper Agent",
  "Cloak and Dagger"
 ],
 "Occult: Crowley And Thelema": [
  "Aleister Crowley",
  "Edward Alexander Crowley",
  "The Great Beast",
  "The Great Beast Six Six Six",
  "To Mega Therion",
  "Do What Thou Wilt",
  "Love Is The Law",
  "Love Under Will",
  "The Book Of The Law",
  "Liber AL Vel Legis",
  "Thelemic Magick",
  "Magick In Theory And Practice",
  "The Holy Guardian Angel",
  "Rose Kelly",
  "Cairo Working",
  "Cairo Nineteen Oh Four",
  "Boleskine House",
  "Loch Ness",
  "Abramelin Operation",
  "The Book Of Abramelin",
  "Abbey Of Thelema",
  "Cefalu Sicily",
  "The Abbey At Cefalu",
  "Leah Hirsig",
  "Scarlet Woman",
  "The Scarlet Woman",
  "Ordo Templi Orientis",
  "The OTO",
  "Argenteum Astrum",
  "The Equinox",
  "Book Of Lies",
  "The Book Of Thoth",
  "Thoth Tarot",
  "Lady Frieda Harris",
  "Nuit Hadit Ra Hoor Khuit",
  "Ra Hoor Khuit",
  "Stele Of Revealing",
  "Aeon Of Horus",
  "Every Man And Every Woman Is A Star",
  "Ninety Three",
  "The Wickedest Man In The World",
  "Gnostic Mass",
  "The Law Of Thelema",
  "Crowley The Great Beast"
 ],
 "Occult: Jack Parsons And Agape Lodge": [
  "Marvel Whiteside Parsons",
  "Jack Parsons Rocket Man",
  "Rocket Man Jack Parsons",
  "The Suicide Squad",
  "Babalon Working",
  "Babalon Working Nineteen Forty Six",
  "Mojave Desert",
  "Agape Lodge",
  "Agape Lodge Of The OTO",
  "The Parsonage",
  "Orange Grove Avenue",
  "Wilfred Talbot Smith",
  "Marjorie Cameron",
  "L Ron Hubbard",
  "Hubbard And Parsons",
  "Allied Enterprises",
  "Liber Forty Nine",
  "The Book Of Babalon",
  "Parsons Crater",
  "Freedom Is A Two Edged Sword"
 ],
 "Occult: Golden Dawn And Rosicrucians": [
  "Hermetic Order Of The Golden Dawn",
  "The Golden Dawn",
  "Samuel Liddell MacGregor Mathers",
  "MacGregor Mathers",
  "William Wynn Westcott",
  "Cipher Manuscripts",
  "Isis Urania Temple",
  "Stella Matutina",
  "Alpha Et Omega",
  "Israel Regardie",
  "Florence Farr",
  "William Butler Yeats",
  "Arthur Edward Waite",
  "Rider Waite Tarot",
  "Pamela Colman Smith",
  "Dion Fortune",
  "Lesser Banishing Ritual Of The Pentagram",
  "The Rosicrucians",
  "Christian Rosenkreuz",
  "Fama Fraternitatis",
  "Confessio Fraternitatis",
  "Chymical Wedding",
  "Rose Cross",
  "Invisible College"
 ],
 "Occult: Hermeticism And Kabbalah": [
  "Hermes Trismegistus",
  "Thrice Great Hermes",
  "Corpus Hermeticum",
  "The Emerald Tablet",
  "As Above So Below",
  "The Kybalion",
  "The Philosophers Stone",
  "Magnum Opus",
  "Prima Materia",
  "Tree Of Life",
  "The Tree Of Life",
  "Ain Soph",
  "Ain Soph Aur",
  "The Qliphoth",
  "Sefer Yetzirah",
  "Shem HaMephorash",
  "Seventy Two Names Of God",
  "Kether The Crown",
  "Chokmah Wisdom",
  "Binah Understanding",
  "Chesed Mercy",
  "Geburah Severity",
  "Tiphareth Beauty",
  "Netzach Victory",
  "Hod Splendour",
  "Yesod The Foundation",
  "Malkuth The Kingdom",
  "Daath The Abyss"
 ],
 "Occult: Freemasonry And Templars": [
  "Grand Lodge",
  "United Grand Lodge Of England",
  "Square And Compass",
  "All Seeing Eye",
  "Great Architect Of The Universe",
  "Hiram Abiff",
  "Widows Son",
  "Master Mason",
  "Entered Apprentice",
  "Fellow Craft",
  "Thirty Third Degree",
  "Scottish Rite",
  "York Rite",
  "Jachin And Boaz",
  "Albert Pike",
  "Morals And Dogma",
  "Knights Templar",
  "Poor Fellow Soldiers Of Christ",
  "Order Of The Temple",
  "Jacques De Molay",
  "Friday The Thirteenth",
  "Rosslyn Chapel",
  "Bavarian Illuminati",
  "Adam Weishaupt"
 ],
 "Occult: Goetia And Grimoires": [
  "Ars Goetia",
  "The Goetia",
  "Lesser Key Of Solomon",
  "Key Of Solomon",
  "Seal Of Solomon",
  "Seventy Two Spirits",
  "Pseudomonarchia Daemonum",
  "Johann Weyer",
  "Grimorium Verum",
  "Grand Grimoire",
  "Book Of Abramelin The Mage",
  "The Necronomicon",
  "Necronomicon By Lovecraft",
  "Abdul Alhazred",
  "Simon Necronomicon",
  "Dictionnaire Infernal",
  "Malleus Maleficarum",
  "Hammer Of Witches",
  "King Bael",
  "Marquis Amon",
  "King Paimon",
  "President Buer",
  "King Beleth",
  "King Purson",
  "Duke Astaroth",
  "King Asmoday",
  "Prince Stolas",
  "President Malphas",
  "King Zagan",
  "King Belial",
  "Duke Dantalion",
  "Lucifuge Rofocale"
 ],
 "Occult: Satanism And Left Hand Path": [
  "Church Of Satan",
  "The Church Of Satan",
  "Anton LaVey",
  "Anton Szandor LaVey",
  "Howard Stanton Levey",
  "The Black Pope",
  "The Satanic Bible",
  "Satanic Bible",
  "The Satanic Rituals",
  "Walpurgisnacht Nineteen Sixty Six",
  "Year One Anno Satanas",
  "Anno Satanas",
  "Black House",
  "California Street",
  "Nine Satanic Statements",
  "Eleven Satanic Rules Of The Earth",
  "Hail Satan",
  "Sigil Of Baphomet",
  "Temple Of Set",
  "Michael Aquino",
  "The Book Of Coming Forth By Night",
  "Order Of Nine Angles",
  "Left Hand Path",
  "Right Hand Path",
  "Eliphas Levi",
  "Baphomet Of Mendes",
  "Goat Of Mendes",
  "Solve Et Coagula",
  "Dogme Et Rituel",
  "Inverted Pentagram"
 ],
 "Occult: Witch Trials And Secret Societies": [
  "Salem Witch Trials",
  "The Salem Witch Trials",
  "Salem Massachusetts",
  "Salem Village",
  "Sixteen Ninety Two",
  "Court Of Oyer And Terminer",
  "Bridget Bishop",
  "Rebecca Nurse",
  "Giles Corey",
  "Sarah Good",
  "Cotton Mather",
  "Samuel Parris",
  "Gallows Hill",
  "Spectral Evidence",
  "Pendle Witches",
  "North Berwick Witch Trials",
  "Matthew Hopkins",
  "Witchfinder General",
  "Hellfire Club",
  "The Hellfire Club",
  "Sir Francis Dashwood",
  "Medmenham Abbey",
  "West Wycombe",
  "Hellfire Caves",
  "Fay Ce Que Vouldras"
 ],
 "Occult: John Dee And Enochian": [
  "John Dee",
  "Doctor John Dee",
  "Edward Kelley",
  "Enochian Magic",
  "Enochian Language",
  "Angelic Language",
  "Enochian Keys",
  "Enochian Calls",
  "The Thirty Aethyrs",
  "The Great Table",
  "Sigillum Dei Aemeth",
  "Liber Loagaeth",
  "Monas Hieroglyphica",
  "The Hieroglyphic Monad",
  "Scrying Mirror",
  "Queen Elizabeths Astrologer",
  "Archangel Uriel",
  "Angel Madimi",
  "Book Of Enoch",
  "Cornelius Agrippa",
  "Three Books Of Occult Philosophy"
 ],
 "Occult: Notable Places": [
  "Glastonbury Tor",
  "Rennes Le Chateau",
  "Brocken Mountain",
  "Salem Massachusetts Sixteen Ninety Two",
  "Abbey Of Thelema Cefalu",
  "Boleskine House Loch Ness",
  "Hellfire Caves West Wycombe",
  "Mortlake Library Of John Dee",
  "Parsonage Pasadena",
  "Church Of Satan San Francisco",
  "Black House California Street",
  "Pasadena Arroyo Seco",
  "Brocken Mountain Harz"
 ],
 "Power: Illuminati": [
  "The Illuminati",
  "Illuminati",
  "Order of the Illuminati",
  "Ingolstadt",
  "Ingolstadt Bavaria",
  "May First Seventeen Seventy Six",
  "Seventeen Seventy Six",
  "The Year Seventeen Seventy Six",
  "Order of Perfectibilists",
  "The Enlightened Ones",
  "Novus Ordo",
  "Owl of Minerva",
  "The Owl of Minerva",
  "Baron Knigge",
  "Secret Society",
  "The Secret Society",
  "The Hidden Hand",
  "The Powers That Be",
  "The Shadow Government",
  "Deep State",
  "The Cabal",
  "The Elite",
  "The Global Elite",
  "Council on Foreign Relations",
  "Trilateral Commission",
  "Club of Rome",
  "Rosicrucians",
  "Order of the Golden Dawn"
 ],
 "Power: Freemasonry": [
  "Freemasonry",
  "Freemasons",
  "The Freemasons",
  "House of the Temple",
  "The House of the Temple",
  "The Thirty Third Degree",
  "Grand Master",
  "Worshipful Master",
  "The Square and Compass",
  "The Great Architect",
  "The Blazing Star",
  "Shriners",
  "The Shriners",
  "Order of the Eastern Star",
  "Knights of Malta",
  "Boaz and Jachin",
  "The Two Pillars",
  "Ordo Ab Chao",
  "Order Out of Chaos"
 ],
 "Power: Elite Clubs": [
  "Skull and Bones Society",
  "The Order of Skull and Bones",
  "Yale University",
  "The Tomb",
  "Bonesmen",
  "Three Hundred Twenty Two",
  "The Bohemian Club",
  "Cremation of Care",
  "Bilderberg",
  "Bilderberg Group",
  "World Economic Forum",
  "Davos",
  "The Great Reset",
  "Federal Reserve",
  "The Federal Reserve",
  "The Rothschilds",
  "House of Rothschild",
  "The Rockefellers",
  "United Nations",
  "The United Nations",
  "Agenda Twenty Thirty",
  "Georgia Guidestones",
  "The Georgia Guidestones",
  "American Stonehenge",
  "Denver Airport",
  "Denver International Airport",
  "Denver Airport Murals",
  "The Blue Horse",
  "Blucifer"
 ],
 "Power: Washington DC": [
  "Washington DC",
  "Washington",
  "District of Columbia",
  "Washington Monument",
  "The Washington Monument",
  "The Obelisk",
  "The Capitol",
  "United States Capitol",
  "Capitol Hill",
  "Capitol Dome",
  "The Apotheosis of Washington",
  "The White House",
  "The Oval Office",
  "Lincoln Memorial",
  "Jefferson Memorial",
  "National Mall",
  "The National Mall",
  "Supreme Court",
  "Statue of Freedom",
  "Statue of Liberty",
  "Lady Liberty",
  "Uncle Sam"
 ],
 "Power: Dollar Symbolism": [
  "Novus Ordo Seclorum",
  "Annuit Coeptis",
  "E Pluribus Unum",
  "In God We Trust",
  "The Great Seal",
  "Great Seal of the United States",
  "The All Seeing Eye",
  "Eye of Providence",
  "The Eye of Providence",
  "The Unfinished Pyramid",
  "The Pyramid",
  "The Capstone",
  "The Bald Eagle",
  "The American Eagle",
  "Thirteen Stars",
  "Thirteen Steps",
  "One Dollar Bill",
  "The Dollar Bill",
  "The Almighty Dollar",
  "Petrodollar",
  "The Phoenix",
  "New World Order",
  "The New World Order",
  "One World Government",
  "Order of the Ages",
  "A New Order of the Ages",
  "Out of Many One"
 ],
 "Power: Vatican": [
  "Vatican",
  "The Vatican",
  "Vatican City",
  "The Holy See",
  "Saint Peters Basilica",
  "Saint Peters Square",
  "Sistine Chapel",
  "The Sistine Chapel",
  "The Pope",
  "Pope",
  "The Papacy",
  "Holy Father",
  "Vicar of Christ",
  "Pontifex Maximus",
  "The Jesuits",
  "Society of Jesus",
  "Ignatius of Loyola",
  "Vatican Archives",
  "Vatican Secret Archives",
  "Vatican Bank",
  "The Conclave",
  "Papal Conclave",
  "Swiss Guard",
  "Opus Dei"
 ],
 "Power: Jerusalem": [
  "The Holy City",
  "The Temple Mount",
  "Dome of the Rock",
  "The Dome of the Rock",
  "Western Wall",
  "The Western Wall",
  "The Wailing Wall",
  "Third Temple",
  "The Third Temple",
  "Al Aqsa Mosque",
  "City of David",
  "The Holy of Holies",
  "The Ark of the Covenant",
  "Red Heifer",
  "The Red Heifer",
  "The Golden Gate",
  "New Jerusalem",
  "Israel",
  "The State of Israel"
 ],
 "Power: World Cities": [
  "City of London",
  "The City of London",
  "The Square Mile",
  "London",
  "The Crown",
  "New York",
  "New York City",
  "The Big Apple",
  "Wall Street",
  "Manhattan",
  "The Eternal City",
  "Rome the Eternal City",
  "Mecca",
  "The Kaaba",
  "Medina",
  "Moscow",
  "Red Square",
  "The Third Rome",
  "Paris",
  "City of Light",
  "Geneva",
  "The Hague",
  "Beijing",
  "Forbidden City",
  "Constantinople",
  "Cairo",
  "Giza",
  "Los Angeles",
  "City of Angels"
 ],
 "Power: Nations": [
  "United States",
  "United States of America",
  "America",
  "The United Kingdom",
  "Great Britain",
  "England",
  "Britannia",
  "Russia",
  "The Russian Federation",
  "China",
  "The Middle Kingdom",
  "Iran",
  "Germany",
  "France",
  "Saudi Arabia",
  "The European Union",
  "NATO",
  "The West",
  "The Superpower",
  "Land of the Free",
  "Home of the Brave",
  "The Promised Land"
 ],
 "Power: End Times Politics": [
  "The End Times",
  "End Times",
  "The Last Days",
  "The Battle of Armageddon",
  "The Antichrist",
  "Antichrist",
  "The Beast",
  "The Beast System",
  "The Great Tribulation",
  "The Rapture",
  "World War Three",
  "The Third World War",
  "Gog and Magog",
  "Cashless Society",
  "Central Bank Digital Currency",
  "Digital ID",
  "Social Credit System",
  "Martial Law",
  "Police State",
  "Population Control",
  "One World Religion",
  "Peace and Safety",
  "Covenant with Many",
  "Abomination of Desolation",
  "The Great Deception",
  "The Final Empire",
  "Revived Roman Empire",
  "Global Governance"
 ],
 "Religions: Hindu Gods And Avatars": [
  "Lord Vishnu",
  "The Trimurti",
  "Om Namah Shivaya",
  "Shiva Nataraja",
  "Durga",
  "Goddess Durga",
  "Lakshmi",
  "Ganesha",
  "Hanuman",
  "Rama",
  "Lord Rama",
  "Sita Ram",
  "Lord Krishna",
  "Hare Krishna",
  "Krishna the Charioteer",
  "Narasimha",
  "Kalki",
  "Kalki Avatar",
  "The Tenth Avatar",
  "Kalki on the White Horse",
  "Dashavatara",
  "Ten Avatars of Vishnu",
  "Yama Lord of Death"
 ],
 "Religions: Hindu Scripture And Cosmology": [
  "Om",
  "The Vedas",
  "Rig Veda",
  "The Upanishads",
  "Song of God",
  "The Mahabharata",
  "The Ramayana",
  "Brahman",
  "Atman",
  "Atman is Brahman",
  "Dharma",
  "Karma",
  "Moksha",
  "Samsara",
  "Maya",
  "The Kali Yuga",
  "Satya Yuga",
  "Age of Darkness",
  "Day of Brahma",
  "Ravana",
  "Ravana the Demon King",
  "Ayodhya",
  "Varanasi",
  "The Ganges",
  "Mother Ganga",
  "Mount Kailash",
  "Kumbh Mela",
  "Diwali",
  "Festival of Lights"
 ],
 "Religions: Islam Names of Allah": [
  "Allah",
  "Allahu Akbar",
  "Bismillah",
  "Bismillah ar Rahman ar Rahim",
  "La Ilaha Illallah",
  "Ninety Nine Names of Allah",
  "Asma ul Husna",
  "Ar Rahman",
  "Ar Rahim",
  "Al Malik",
  "Al Quddus",
  "As Salam",
  "Al Aziz",
  "Al Jabbar",
  "Al Khaliq",
  "Al Ghaffar",
  "Al Wahhab",
  "Al Alim",
  "Al Hakim",
  "Al Haqq",
  "Al Nur",
  "Al Hadi",
  "Al Ahad",
  "As Samad",
  "Al Qayyum",
  "Alhamdulillah",
  "Tawhid"
 ],
 "Religions: Islam Prophets And Holy Places": [
  "Muhammad",
  "Prophet Muhammad",
  "The Prophet Muhammad",
  "Seal of the Prophets",
  "Rasul Allah",
  "Ibrahim",
  "Prophet Ibrahim",
  "Musa",
  "Prophet Musa",
  "Isa",
  "Isa ibn Maryam",
  "Jibril",
  "Angel Jibril",
  "Israfil",
  "Azrael",
  "The Quran",
  "The Holy Quran",
  "Hadith",
  "Sharia",
  "Masjid Al Haram",
  "Black Stone",
  "Zamzam",
  "Mount Arafat",
  "Hajj",
  "Al Aqsa",
  "Masjid Al Aqsa",
  "Isra and Miraj",
  "Night Journey",
  "Ramadan",
  "Laylat Al Qadr",
  "Night of Power",
  "Karbala",
  "Imam Husayn",
  "Ali ibn Abi Talib"
 ],
 "Religions: Islamic End Times": [
  "Yawm Al Qiyamah",
  "Day of Qiyamah",
  "Qiyamah",
  "Day of Judgment",
  "Yawm ad Din",
  "The Hour",
  "Signs of the Hour",
  "Mahdi",
  "The Mahdi",
  "Imam Mahdi",
  "The Hidden Imam",
  "Return of Isa",
  "Dajjal",
  "The Dajjal",
  "Al Masih ad Dajjal",
  "The False Messiah",
  "One Eyed Dajjal",
  "Yajuj and Majuj",
  "The Sufyani",
  "Beast of the Earth",
  "Dabbat Al Ard",
  "Trumpet of Israfil",
  "Sirat Bridge",
  "As Sirat",
  "Jannah",
  "Jahannam",
  "Iblis",
  "Shaytan",
  "Shaitan the Accursed",
  "Jinn",
  "The Jinn"
 ],
 "Religions: Buddhism": [
  "Buddha",
  "The Buddha",
  "Gautama Buddha",
  "Siddhartha",
  "Siddhartha Gautama",
  "Shakyamuni Buddha",
  "The Enlightened One",
  "The Awakened One",
  "Nirvana",
  "Enlightenment",
  "Dharma Wheel",
  "Sangha",
  "The Three Jewels",
  "The Four Noble Truths",
  "Eightfold Path",
  "The Noble Eightfold Path",
  "The Middle Way",
  "Dukkha",
  "Bodhi Tree",
  "Bodh Gaya",
  "Lumbini",
  "Sarnath",
  "Maitreya",
  "Maitreya Buddha",
  "The Future Buddha",
  "Avalokiteshvara",
  "Bodhisattva",
  "Mara",
  "Mara the Tempter",
  "Mara the Evil One",
  "Om Mani Padme Hum",
  "Pure Land",
  "Zen",
  "Dalai Lama",
  "Shambhala"
 ],
 "Religions: Sikhism And Jainism": [
  "Sikhism",
  "Guru Nanak",
  "Guru Nanak Dev",
  "Guru Gobind Singh",
  "Waheguru",
  "Ik Onkar",
  "Sat Nam",
  "Sat Sri Akal",
  "Guru Granth Sahib",
  "Golden Temple",
  "Harmandir Sahib",
  "Amritsar",
  "Khalsa",
  "The Khalsa",
  "Mul Mantar",
  "Gurdwara",
  "Jainism",
  "Mahavira",
  "Lord Mahavira",
  "Rishabhanatha",
  "Parshvanatha",
  "Tirthankara",
  "Twenty Four Tirthankaras",
  "Jina",
  "Ahimsa",
  "Kevala Jnana",
  "Siddhashila",
  "Digambara",
  "Svetambara",
  "Namokar Mantra"
 ],
 "Religions: Zoroastrianism": [
  "Zarathustra",
  "Prophet Zarathustra",
  "Zoroastrianism",
  "Wise Lord",
  "Angra Mainyu",
  "The Evil Spirit",
  "Spenta Mainyu",
  "Amesha Spentas",
  "The Lie",
  "Good Thoughts Good Words Good Deeds",
  "Saoshyant",
  "The Saoshyant",
  "Astvat Ereta",
  "Frashokereti",
  "The Final Renovation",
  "Chinvat Bridge",
  "Avesta",
  "The Gathas",
  "Anahita",
  "Azi Dahaka",
  "Zahhak",
  "Fire Temple",
  "Faravahar",
  "The Magi"
 ],
 "Religions: Taoism And Shinto": [
  "Tao",
  "The Tao",
  "Tao Te Ching",
  "Lao Tzu",
  "Laozi",
  "Zhuangzi",
  "Yin and Yang",
  "Yin Yang",
  "Wu Wei",
  "The Way",
  "The Way and its Power",
  "Jade Emperor",
  "Three Pure Ones",
  "Eight Immortals",
  "Mount Tai",
  "Shinto",
  "Kami",
  "Amaterasu",
  "Amaterasu Omikami",
  "Sun Goddess",
  "Susanoo",
  "Izanagi",
  "Izanami",
  "Inari",
  "Ise Grand Shrine",
  "Mount Fuji",
  "Torii Gate",
  "Yomi"
 ],
 "Religions: Jewish Mysticism And Tradition": [
  "Talmud",
  "The Talmud",
  "Mishnah",
  "Midrash",
  "Torah",
  "Zohar",
  "The Zohar",
  "Kabbalah",
  "Kabbalah Tree of Life",
  "Sefirot",
  "Ein Sof",
  "Shekhinah",
  "The Shekhinah",
  "Adam Kadmon",
  "Tzimtzum",
  "Tikkun Olam",
  "Moshiach",
  "Moshiach ben David",
  "Moshiach ben Yosef",
  "King Messiah",
  "The World to Come",
  "Armilus",
  "Samael",
  "Lilith",
  "Sitra Achra",
  "Golem",
  "Golem of Prague",
  "Rabbi Loew",
  "The Ari",
  "Baal Shem Tov",
  "Shema Yisrael",
  "The Kotel"
 ],
 "Religions: Gnosticism": [
  "Gnosis",
  "Gnosticism",
  "The Gnostics",
  "Sophia",
  "Pistis Sophia",
  "Fall of Sophia",
  "The Demiurge",
  "Demiurge",
  "Yaldabaoth",
  "Samael the Blind God",
  "The Archons",
  "Archons",
  "Pleroma",
  "The Pleroma",
  "The Monad",
  "The Unknown Father",
  "Abraxas",
  "Christ the Aeon",
  "Divine Spark",
  "The Divine Spark",
  "Nag Hammadi Library",
  "Gospel of Thomas",
  "Gospel of Judas",
  "Apocryphon of John",
  "Simon Magus",
  "Mani",
  "Manichaeism",
  "The Cathars"
 ],
 "Religions: Bahai Mandaean And Yazidi": [
  "Bahai Faith",
  "Bahaullah",
  "The Bab",
  "Abdul Baha",
  "The Glory of God",
  "Shrine of the Bab",
  "Bahai Gardens",
  "Promised One of All Ages",
  "Most Great Peace",
  "Mandaeans",
  "Mandaeism",
  "John the Baptist",
  "Yahya Yuhana",
  "Ginza Rba",
  "The Great Life",
  "World of Light",
  "World of Darkness",
  "Ruha",
  "Yazidis",
  "Yazidism",
  "Melek Taus",
  "Peacock Angel",
  "Tawusi Melek",
  "Sheikh Adi",
  "Lalish",
  "Seven Angels",
  "Mount Sinjar"
 ],
 "Religions: Messiahs And Adversaries": [
  "The Coming Messiah",
  "Messiah of the Last Days",
  "World Teacher",
  "The Promised One",
  "The Last Avatar",
  "The Future Savior",
  "Savior of the World",
  "Renewal of the World",
  "End of the Age",
  "The Last Judgment",
  "The Great Deceiver",
  "The Adversary",
  "Lord of Darkness",
  "Prince of Darkness",
  "King of Demons",
  "Asmodeus",
  "Belial",
  "Mastema",
  "The Wheel of Time",
  "Age of Truth Returns",
  "Golden Age Restored"
 ],
 "UFO: Famous Incidents": [
  "Roswell Crash",
  "Roswell Weather Balloon",
  "The Roswell Debris",
  "Kenneth Arnold",
  "Kenneth Arnold Sighting",
  "Mount Rainier Sighting",
  "Flying Saucers",
  "Flying Saucer",
  "The Flying Saucer",
  "Phoenix Lights",
  "The Phoenix Lights",
  "Rendlesham Forest",
  "The Rendlesham Forest Incident",
  "Britains Roswell",
  "Tic Tac UFO",
  "The Tic Tac UFO",
  "Nimitz Encounter",
  "The Nimitz Encounter",
  "USS Nimitz",
  "Tic Tac Encounter",
  "Washington Flap",
  "Washington Flap Nineteen Fifty Two",
  "UFOs Over Washington",
  "Betty and Barney Hill",
  "The Hill Abduction",
  "Travis Walton"
 ],
 "UFO: Government Programs": [
  "Project Bluebook",
  "Project Sign",
  "Project Grudge",
  "AATIP",
  "AARO",
  "Advanced Aerospace Threat Identification Program",
  "All Domain Anomaly Resolution Office",
  "UAP Task Force",
  "The UAP Task Force",
  "Condon Report",
  "The Condon Report",
  "Robertson Panel",
  "The Robertson Panel",
  "Estimate of the Situation",
  "Project Twinkle",
  "Advanced Aviation Threat",
  "UAP Report",
  "The UAP Report",
  "UAP Hearing",
  "Congressional UAP Hearing",
  "UAP Disclosure Act",
  "Unidentified Aerial Phenomena",
  "Unidentified Anomalous Phenomena",
  "Unidentified Flying Object",
  "Unidentified Flying Objects",
  "Swamp Gas"
 ],
 "UFO: Conspiracy Lore": [
  "Blue Beam Conspiracy",
  "Project Blue Beam Theory",
  "Fake Alien Invasion",
  "Staged Alien Invasion",
  "Holographic Sky",
  "Paradise Ranch",
  "S Four",
  "Papoose Lake",
  "Janet Airlines",
  "The Black Mailbox",
  "Majestic Twelve Documents",
  "MJ Twelve",
  "Operation Majestic Twelve",
  "Dulce Base",
  "The Dulce Base",
  "Dulce New Mexico",
  "Underground Base",
  "Deep Underground Military Base",
  "Secret Space Program",
  "Men in Black",
  "The Men in Black"
 ],
 "UFO: Crashed Saucers and Tech": [
  "Crashed Saucer",
  "Crashed Saucers",
  "Crash Retrieval",
  "Crash Retrieval Program",
  "Reverse Engineering",
  "Reverse Engineered",
  "Alien Technology",
  "Alien Tech",
  "Nonhuman Intelligence",
  "Non Human Intelligence",
  "Nonhuman Biologics",
  "Nonhuman Craft",
  "Recovered Craft",
  "Recovered Bodies",
  "Alien Bodies",
  "Alien Craft",
  "Flying Disc",
  "Flying Discs",
  "The Flying Disc",
  "Disc Shaped Craft",
  "Cigar Shaped Craft",
  "Mothership",
  "The Mothership",
  "Anti Gravity",
  "Antigravity Propulsion",
  "Gravity Propulsion",
  "Element One Fifteen",
  "Zero Point Energy",
  "Free Energy"
 ],
 "UFO: Alien Types": [
  "Greys",
  "The Greys",
  "Grey Aliens",
  "Little Grey Men",
  "Little Green Men",
  "Tall Greys",
  "Zeta Reticuli",
  "Zeta Reticulans",
  "Reptilians",
  "The Reptilians",
  "Reptilian Overlords",
  "Draconians",
  "Lizard People",
  "Nordics",
  "The Nordics",
  "Tall Whites",
  "Pleiadians",
  "The Pleiadians",
  "Arcturians",
  "Sirians",
  "Mantis Beings",
  "Insectoids",
  "The Nephilim",
  "Watchers",
  "The Watchers",
  "Fallen Angels"
 ],
 "UFO: Ancient Astronauts": [
  "Ancient Astronauts",
  "Ancient Astronaut Theory",
  "Erich von Daniken",
  "Chariots of the Gods",
  "Nazca Lines",
  "The Nazca Lines",
  "Nazca Astronaut",
  "Great Pyramid",
  "Pumapunku",
  "Baalbek",
  "Sumerian Tablets",
  "Twelfth Planet",
  "The Twelfth Planet",
  "Zecharia Sitchin",
  "Ezekiels Wheel",
  "Wheel Within a Wheel",
  "Vimanas",
  "Vimana",
  "Dogon Tribe",
  "Sirius Mystery",
  "Palenque Astronaut",
  "Pacal Sarcophagus",
  "Stone Heads",
  "Easter Island",
  "Moai",
  "Crystal Skulls",
  "Baghdad Battery"
 ],
 "UFO: Abductions and Contactees": [
  "Alien Abduction",
  "Alien Abductions",
  "Abductee",
  "Abductees",
  "Missing Time",
  "Close Encounter",
  "Close Encounters",
  "Close Encounters of the Third Kind",
  "Close Encounter of the Fourth Kind",
  "Close Encounter of the Fifth Kind",
  "Contactee",
  "Contactees",
  "Contactee Movement",
  "George Adamski",
  "Billy Meier",
  "Venusian",
  "Space People",
  "Channeling",
  "Telepathic Contact",
  "Hypnotic Regression",
  "Star Map",
  "Marjorie Fish Star Map",
  "Probed",
  "Anal Probe",
  "Sleep Paralysis",
  "Bedroom Visitors",
  "Abduction Phenomenon",
  "Hybrid Babies",
  "Communion"
 ],
 "UFO: Disclosure Phrases": [
  "Disclosure",
  "Disclosure Day",
  "Full Disclosure",
  "The Disclosure",
  "Disclosure Project",
  "Soft Disclosure",
  "They Are Here",
  "We Are Not Alone",
  "The Truth Is Out There",
  "I Want to Believe",
  "Trust No One",
  "Deny Everything",
  "Believe",
  "Watch the Skies",
  "Keep Watching the Skies",
  "Not of This World",
  "Out of This World",
  "Visitors From Space",
  "Aliens Are Real",
  "UFOs Are Real",
  "The Phenomenon",
  "The Age of Disclosure",
  "Alien Invasion",
  "Invasion From Mars",
  "War of the Worlds",
  "The Day the Earth Stood Still",
  "Klaatu Barada Nikto",
  "Phone Home"
 ],
 "UFO: Sky Phenomena": [
  "The Foo Fighters",
  "Foo Fighters World War Two",
  "Ghost Rockets",
  "Ball Lightning",
  "Orbs",
  "Sky Orbs",
  "Glowing Orbs",
  "Marfa Lights",
  "Hessdalen Lights",
  "Min Min Lights",
  "Earth Lights",
  "Crop Circles",
  "Crop Circle",
  "Mystery Airships",
  "Phantom Airships",
  "Airship Wave",
  "Green Fireballs",
  "Mystery Drones",
  "Drone Swarm",
  "New Jersey Drones",
  "Strange Lights",
  "Lights in the Sky",
  "Silver Disc",
  "Glowing Disc",
  "Sky Quake",
  "Chemtrails",
  "Skyquakes",
  "Cloud Ships"
 ],
 "UFO: SETI and Science": [
  "SETI",
  "SETI Institute",
  "Search for Extraterrestrial Intelligence",
  "Wow Signal",
  "The Wow Signal",
  "Big Ear Telescope",
  "Oumuamua",
  "Interstellar Object",
  "Interstellar Visitor",
  "Fermi Paradox",
  "The Fermi Paradox",
  "Where Is Everybody",
  "Drake Equation",
  "The Drake Equation",
  "Great Filter",
  "The Great Filter",
  "Dark Forest",
  "Dark Forest Theory",
  "Zoo Hypothesis",
  "Rare Earth",
  "Kardashev Scale",
  "Dyson Sphere",
  "Tabbys Star",
  "Arecibo Message",
  "Arecibo Telescope",
  "Golden Record",
  "Pioneer Plaque",
  "Breakthrough Listen"
 ]
};
