// Curated phrase lists, generated variations and explanatory notes.
import RESEARCH from './research.js';

export const LISTS = {
  holy: ['God','Jesus','Jesus Christ','Christ','Messiah','Yahweh','Jehovah','Elohim','Adonai','El Shaddai','Emmanuel','Immanuel','Holy Spirit','Holy Ghost','Lamb of God','Son of God','Son of Man','King of Kings','Lord of Lords','Alpha and Omega','Prince of Peace','Word of God','Lion of Judah','Good Shepherd','Savior','Redeemer','Most High','Ancient of Days','Michael','Gabriel','Raphael','Mary','Joseph','Peter','Paul','John','Moses','Abraham','David','Elijah','Yeshua','ישוע','יהוה','Ἰησοῦς','Χριστός','ישוע המשיח','One Five Three','One Hundred Fifty Three','One Hundred and Fifty Three','Hundred Fifty Three','One Fifty Three','One Five Three Fish','One Hundred Fifty Three Fish','One Hundred and Fifty Three Fish','Hundred and Fifty Three Great Fish','Great Fishes One Hundred Fifty Three'],
  unholy: ['Satan','Devil','Lucifer','Beelzebub','Belial','Mammon','Moloch','Baal','Leviathan','Antichrist','Beast','Serpent','Dragon','Abaddon','Apollyon','Asmodeus','Azazel','Lilith','Judas','Jezebel','Nimrod','False Prophet','Man of Sin','Son of Perdition','Mark of the Beast','Whore of Babylon','Prince of Darkness','Father of Lies','Ἀντίχριστος','שטן'],
  nations: ['Israel','Judah','Babylon','Egypt','Assyria','Persia','Greece','Rome','Edom','Moab','Gog','Magog','America','United States','England','Britain','France','Germany','Russia','China','India','Iran','Iraq','Syria','Turkey','Italy','Spain','Japan','Europe','Vatican','Jerusalem','Zion'],
};
const TITLES = ['King of','Prince of','Lord of','Beast of','Savior of','Light of'];
const HOLY_NAMES = ['Jesus','Jesus Christ','Christ','Lord Jesus','Yeshua','Messiah','Jesus the Christ','Jesus of Nazareth'];
const EPITHETS = ['Son of David','Son of God','Son of Man','Son of Mary','Son of Joseph','King of Kings','Lord of Lords','King of the Jews','King of Israel','King of Glory','Lamb of God','Lion of Judah','Word of God','Light of the World','Bread of Life','Prince of Peace','Alpha and Omega','the Good Shepherd','the Messiah','the Savior','the Redeemer','the Lord','our Lord','our Savior','the Son of God','the Holy One','the Way the Truth and the Life','the Resurrection and the Life','Almighty','Emmanuel',
  'Giver of Life','Giver of Eternal Life','Lord of Life','Prince of Life','Return from the Dead','Returned from the Dead','Risen from the Dead','Rose from the Dead','Raised from the Dead','the Risen One','Conqueror of Death','Destroyer of Death','Firstborn from the Dead','God of Creation','God of Salvation','God of Life','Second Coming','Returns in Glory','Judge of the Living and the Dead',
  'Timeless Salvation','Eternal Salvation','Son of Salvation','Son of Righteousness','Sun of Righteousness','Son of the Most High','Holy One of Israel','Author of Life','Author of Salvation','Light of Life','Bright Morning Star','Righteous One','Anointed One','Chosen One','Timeless King','Eternal King','King Eternal','Everlasting Father','Everlasting Life','Eternal Life','Timeless Life','Giver of Timeless Life','Destroyer of Destruction','Victor over Death','Hope of Glory'];
const UNHOLY_NAMES = ['Satan','Lucifer','the Devil','Beelzebub','Antichrist','the Beast','the Dragon','Abaddon','Apollyon','Belial'];
const UNHOLY_EPITHETS = ['God of Destruction','God of Death','God of Darkness','God of This World','God of War','Lord of Destruction','Lord of Death','Lord of Darkness','Lord of the Flies','Prince of Darkness','Prince of This World','Prince of the Air','Father of Lies','Destroyer of Worlds','Bringer of Death','Angel of Death','Angel of Light','King of the Abyss','Ruler of Hell','Return from the Dead','Returned from the Dead','Returns from the Dead','Risen from the Dead','Rise from the Pit','Risen from the Abyss','Back from the Dead','Resurrected','the Deceiver','the Accuser','the Adversary','the Destroyer','the Tempter','the Morning Star','Son of Perdition',
  'Timeless Destruction','Eternal Destruction','Endless Destruction','Ancient Destruction','Everlasting Destruction','Son of Destruction','Child of Destruction','Father of Destruction','Bringer of Destruction','Lord of Ruin','God of Ruin','Timeless Darkness','Eternal Darkness','Son of Darkness','Son of Satan','Son of the Devil','Abomination of Desolation','Man of Lawlessness','Man of Sin','Lawless One','Evil One','Wicked One','Great Deceiver','Old Serpent','Great Dragon','Fallen Angel','Fallen One','Destroyer','Deceiver','Beast from the Sea','Beast from the Earth','Beast from the Abyss'];
const JUDGES = ['God','Jesus','Jesus Christ','the Lord','Christ','Michael','the Lamb','the Most High'];
const JUDGE_VERBS = ['punishes','punished','punishing','judges','judged','judging','destroys','destroyed','destroying','defeats','defeated','defeating','binds','bound','binding','casts out','cast out','casting out','crushes','crushed','crushing','rebukes','rebuked','rebuking','condemns','condemned','condemning','conquers','conquered','conquering','overthrows','overthrew'];
const JUDGED = ['Satan','the Devil','a Devil','Lucifer','the Beast','the Dragon','the Serpent','the Antichrist','Beelzebub','Demons','the Demon'];
const JUDGE_PHRASES = ['Punishment of the Devil','Punishment of Satan','Judgment of Satan','Judgment of the Devil','Defeat of Satan','Fall of Lucifer','Fall of Satan','Satan Cast into the Lake of Fire','Devil Cast into the Lake of Fire','Lake of Fire','Bottomless Pit','Satan Bound for a Thousand Years','The Lord Rebuke Thee','The Lord Rebuke You Satan','Get Thee Behind Me Satan','Serpent Head Crushed','Crushing the Serpent','Wrath of God','Day of Judgment','Day of the Lord','Victory over Satan','Victory over the Devil'];
// user-supplied phrases, grouped by theme; variations are generated below
const PHRASES = {
  'Lion of Judah': ['Lion of Judah Blast Off','Lion of Judah Talented','Lion of Judah Rises','Lion of Judah Roars','Lion of Judah Returns','Lion of Judah Has Come','Lion of Judah Victorious','Lion of Judah Anointed','Lion of Judah Chosen','Lion of Judah Gifted'],
  'Heaven & salvation': ['The Access into Heaven','Access into Heaven','Access to Heaven','The Gate of Heaven','She Gets into Heaven','She Got into Heaven','She Will Get into Heaven','Shes Going to Be Saved','She Is Going to Be Saved','She Will Be Saved','She Is Saved','Shes Saved','Saved by Grace','Going to Heaven'],
  'Revelation': ['Secret Is Revealed God','The Secret Is Revealed','Secret Revealed','God Reveals the Secret','The Secret of God','Hidden Things Revealed','The Mystery Revealed','Revealed by God',
    'Revealing the Secret','Reveal the Secret','Reveals the Secret','Revealed the Secret','Revealing a Secret','Revealing Secrets','Revealing the Secrets','Revealing the Hidden Secret','Revealing the Secret of God','Revealing Gods Secret','God Revealing the Secret','God Reveals the Secret','She Is Revealing the Secret','Shes Revealing the Secret','She Reveals the Secret','She Revealed the Secret','The Revealing of the Secret','Secret Revealing','The Secret Revealing','Revealing the Mystery','Unveiling the Secret','Exposing the Secret','Disclosing the Secret','Uncovering the Secret','Revealing the Truth','Revealing the Hidden Truth'],
  'Bride': ['Jealous of Me Real Bride','Jealous of Me the Real Bride','Jealous of Me True Bride','Jealous of the Real Bride','Jealous of the True Bride','Jealous of Real Bride','Jealous of Her Real Bride','Jealous of His Real Bride','Jealous of My Real Bride','Jealous of Me Real Groom','Jealous of Me Real Husband','Jealous of Me Real Wife','Envious of Me Real Bride','Envious of the Real Bride','Jealousy of the Real Bride','They Are Jealous of the Real Bride','They Are Jealous of Me','She Is Jealous of the Real Bride','She Is the Real Bride','Shes the Real Bride','She Is the True Bride','I Am the Real Bride','The Real Bride','The True Bride','Real Bride of Christ','True Bride of Christ','The Bride of Christ','The Bride of the Lamb','The Chosen Bride','The Rightful Bride','The False Bride','Jealous of the Bride of Christ'],
  'JC warning': ['Stop Pissin JC Off', 'Stop Pissing JC Off', 'Stop Pissin Off JC', 'Stop Pissing Off JC', 'Quit Pissin JC Off', 'Quit Pissing JC Off', 'Dont Piss JC Off', 'Pissin JC Off', 'Pissing JC Off', 'Youre Pissin JC Off', 'Youre Pissing JC Off', 'Stop Angering JC', 'Stop Making JC Mad', 'Stop Making JC Angry', 'Stop Provoking JC', 'Stop Upsetting JC', 'Stop Pissin Jesus Christ Off', 'Stop Pissing Jesus Christ Off', 'Stop Pissin Off Jesus Christ', 'Stop Pissing Off Jesus Christ', 'Quit Pissin Jesus Christ Off', 'Quit Pissing Jesus Christ Off', 'Dont Piss Jesus Christ Off', 'Pissin Jesus Christ Off', 'Pissing Jesus Christ Off', 'Youre Pissin Jesus Christ Off', 'Youre Pissing Jesus Christ Off', 'Stop Angering Jesus Christ', 'Stop Making Jesus Christ Mad', 'Stop Making Jesus Christ Angry', 'Stop Provoking Jesus Christ', 'Stop Upsetting Jesus Christ', 'Stop Pissin Jesus Off', 'Stop Pissing Jesus Off', 'Stop Pissin Off Jesus', 'Stop Pissing Off Jesus', 'Quit Pissin Jesus Off', 'Quit Pissing Jesus Off', 'Dont Piss Jesus Off', 'Pissin Jesus Off', 'Pissing Jesus Off', 'Youre Pissin Jesus Off', 'Youre Pissing Jesus Off', 'Stop Angering Jesus', 'Stop Making Jesus Mad', 'Stop Making Jesus Angry', 'Stop Provoking Jesus', 'Stop Upsetting Jesus', 'Stop Pissin Christ Off', 'Stop Pissing Christ Off', 'Stop Pissin Off Christ', 'Stop Pissing Off Christ', 'Quit Pissin Christ Off', 'Quit Pissing Christ Off', 'Dont Piss Christ Off', 'Pissin Christ Off', 'Pissing Christ Off', 'Youre Pissin Christ Off', 'Youre Pissing Christ Off', 'Stop Angering Christ', 'Stop Making Christ Mad', 'Stop Making Christ Angry', 'Stop Provoking Christ', 'Stop Upsetting Christ', 'Stop Pissin God Off', 'Stop Pissing God Off', 'Stop Pissin Off God', 'Stop Pissing Off God', 'Quit Pissin God Off', 'Quit Pissing God Off', 'Dont Piss God Off', 'Pissin God Off', 'Pissing God Off', 'Youre Pissin God Off', 'Youre Pissing God Off', 'Stop Angering God', 'Stop Making God Mad', 'Stop Making God Angry', 'Stop Provoking God', 'Stop Upsetting God', 'Stop Pissin the Lord Off', 'Stop Pissing the Lord Off', 'Stop Pissin Off the Lord', 'Stop Pissing Off the Lord', 'Quit Pissin the Lord Off', 'Quit Pissing the Lord Off', 'Dont Piss the Lord Off', 'Pissin the Lord Off', 'Pissing the Lord Off', 'Youre Pissin the Lord Off', 'Youre Pissing the Lord Off', 'Stop Angering the Lord', 'Stop Making the Lord Mad', 'Stop Making the Lord Angry', 'Stop Provoking the Lord', 'Stop Upsetting the Lord'],
  'Vaccines': ['The Vaccines Not Be Safe', 'The Vaccines Be Not Safe', 'The Vaccines Not Safe', 'The Vaccines Are Not Safe', 'The Vaccines Arent Safe', 'The Vaccines Are Unsafe', 'The Vaccines Are Safe', 'The Vaccines Be Safe', 'The Vaccines Not Be Safe at All', 'The Vaccine Not Be Safe', 'The Vaccine Be Not Safe', 'The Vaccine Not Safe', 'The Vaccine Is Not Safe', 'The Vaccine Isnt Safe', 'The Vaccine Is Unsafe', 'The Vaccine Is Safe', 'The Vaccine Be Safe', 'The Vaccine Not Be Safe at All', 'Vaccines Not Be Safe', 'Vaccines Be Not Safe', 'Vaccines Not Safe', 'Vaccines Are Not Safe', 'Vaccines Arent Safe', 'Vaccines Are Unsafe', 'Vaccines Are Safe', 'Vaccines Be Safe', 'Vaccines Not Be Safe at All', 'The Vax Not Be Safe', 'The Vax Be Not Safe', 'The Vax Not Safe', 'The Vax Is Not Safe', 'The Vax Isnt Safe', 'The Vax Is Unsafe', 'The Vax Is Safe', 'The Vax Be Safe', 'The Vax Not Be Safe at All', 'The Jab Not Be Safe', 'The Jab Be Not Safe', 'The Jab Not Safe', 'The Jab Is Not Safe', 'The Jab Isnt Safe', 'The Jab Is Unsafe', 'The Jab Is Safe', 'The Jab Be Safe', 'The Jab Not Be Safe at All', 'The Shot Not Be Safe', 'The Shot Be Not Safe', 'The Shot Not Safe', 'The Shot Is Not Safe', 'The Shot Isnt Safe', 'The Shot Is Unsafe', 'The Shot Is Safe', 'The Shot Be Safe', 'The Shot Not Be Safe at All'],
  'Identity': ['I Am the Female Savior', 'I Am the Savior', 'I Am the Male Savior', 'She Is the Female Savior', 'The Female Savior', 'A Female Savior', 'I Am Project Monarch', 'I Was Project Monarch', 'She Is Project Monarch', 'Project Monarch Survivor', 'All Believe I Am Lucifer', 'All Believe Im Lucifer', 'They All Believe I Am Lucifer', 'Everyone Believes I Am Lucifer', 'All Believe She Is Lucifer', 'All Believe I Am God', 'All Believe I Am the Devil', 'Evil Cant Accept Im God', 'Evil Cant Accept I Am God', 'Evil Cannot Accept Im God', 'Evil Cannot Accept I Am God', 'Evil Cant Accept She Is God', 'The Devil Cant Accept Im God', 'Satan Cant Accept Im God'],
  'Visions': ['Vision of Comedies', 'Vision of Comedy', 'Visions of Comedies', 'Vision of Meeting', 'Vision of the Meeting', 'Vision of a Meeting', 'Visions of Meeting', 'Vision of the Mind', 'Visions of the Mind', 'A Vision of the Mind', 'Vision of Mind'],
  'Esoteric & lore': ['AI Dissolving Self', 'AI Dissolving the Self', 'AI Dissolves Self', 'AI Dissolving Itself', 'The AI Dissolving Self', 'Divine Genes Snakes', 'Divine Snake Genes', 'Divine Serpent Genes', 'Divine Genes Serpents', 'Snake Genes', 'Akhenaten Dead Forever', 'Akhenaten Is Dead Forever', 'Akhenaten Dead', 'Akhenaten Lives Forever', 'Akhenaten Returns', 'In Hoc Signo Vinces', 'In This Sign Conquer', 'In This Sign You Will Conquer', 'Dracone Bona Dividebant', 'Big Foot Shaved Clone', 'Bigfoot Shaved Clone', 'Bigfoot Clone', 'Shaved Bigfoot', 'The Skies Are Alive', 'Skies Are Alive', 'The Sky Is Alive', 'Cabal Eviction Notice', 'The Cabal Eviction Notice', 'Eviction of the Cabal', 'The Cabal Evicted', 'Jeppesen Terminal', 'The Jeppesen Terminal', 'Denver Airport Jeppesen Terminal', 'Vietnamese Is King', 'Vietnam Is King', 'The Vietnamese Are Kings'],
  'Names': ['Homer John Thomas', 'Peterick Johnson', 'Senator John McCain', 'John McCain', 'John Sidney McCain'],
  'Six six six': ['Number Six Six Six', 'Six Six Six Number', 'The Number Six Six Six', 'Six Six Six the Number', 'Six Six Six', 'Triple Six', 'Triple Six Number', 'Six Hundred Sixty Six', 'Six Hundred and Sixty Six', 'Number Six Hundred Sixty Six', 'The Number Six Hundred Sixty Six', 'His Number Is Six Six Six', 'Its Number Is Six Six Six', 'The Number of the Beast', 'Number of the Beast Six Six Six', 'Six Six Six the Number of the Beast', 'The Mark Six Six Six', 'Mark of Six Six Six', 'Holy Number Six', 'Number Six'],
  'Truth & reversal': ['Revelation of Truth', 'The Revelation of Truth', 'Revelation of the Truth', 'Revelations of Truth', 'Truth Revealed', 'Learn to Think Backwards', 'Backwards Learn to Think', 'Learning to Think Backwards', 'Learn to Think in Reverse', 'Think Backwards', 'Reverse Foreclosure', 'The Reverse Foreclosure', 'Evil Cannot Be Trusted', 'Evil Cant Be Trusted', 'Evil Can Never Be Trusted', 'The Devil Cannot Be Trusted', 'Satan Cannot Be Trusted', 'I No Answer a Demon Scream', 'I Do Not Answer a Demon Scream', 'I Dont Answer a Demons Scream', 'I Answer No Demon Scream'],
  'Everyday': ['Do Is Not Mandatory', 'It Is Not Mandatory', 'Not Mandatory', 'Im Burning My Books', 'I Am Burning My Books', 'Burning My Books', 'Im So Sorry Renne', 'I Am So Sorry Renne', 'My Armpit Stinks', 'My Armpits Stink', 'My Pink Lotus Life', 'Pink Lotus Life', 'The Pink Lotus', 'Playful Teasing Lol', 'Playful Teasing', 'Thank You All Is on AI', 'Thank You All', 'All Is on AI', 'Pinkie Pie Le Dijo Smile', 'Pinkie Pie Said Smile', 'A Two Peas in a Pod', 'Two Peas in a Pod', 'Like Two Peas in a Pod', 'Let It Be So Now', 'Let It Be So', 'So Let It Be', 'Brooks Was Heard', 'Brooks Was Here', 'Fantastic Woman', 'A Fantastic Woman', 'The Fantastic Woman', 'Not a Show Ariana', 'It Is Not a Show', 'I Would Slam Him', 'I Would Slam Her', 'Daisy Josephine', 'My Promise to You', 'My Promise to You All', 'Our Promise to You', 'A Promise to You', 'Sorry and Thank You', 'Im Sorry and Thank You', 'Thank You and Sorry', 'So Lets Make It Shall We', 'Lets Make It Shall We', 'So Shall We Make It', 'Less Than a Week Tik Tok', 'Less Than a Week', 'Gad Zooks or Gadzooks', 'Gadzooks', 'The Ultra Livestream', 'Ultra Livestream'],
  'Sexuality': ['Truly Homosexual', 'Truly a Homosexual', 'Homosexual Truly', 'She Is Truly Homosexual', 'Shes Truly Homosexual', 'Truly Gay', 'Truly Lesbian', 'Truly Bisexual', 'Truly Heterosexual', 'Truly Straight', 'Truly Asexual', 'Secretly Homosexual', 'Openly Homosexual'],
  'Crude': ['Pissflaps Dawn', 'Pissflaps', 'Kill Me Now or Get Fucked', 'Kill Me Now or Get Fucked Up', 'Kill Me or Get Fucked', 'Kill Me Now'],
  'Nero & decoding': ['נרון קסר', 'נרו קסר', 'Decode NRWN QSR', 'Decode NRWNQSR', 'NRWN QSR', 'Nero Caesar', 'Neron Kaisar', 'Neron Qesar', 'Nero Caesar Six Six Six', 'Decode Nero Caesar', 'Decode the Number'],
  'Royalty & Egypt': ['Pharaohs Crown', 'The Pharaohs Crown', 'Crown of Pharaoh', 'Crown of the Pharaoh', 'Wonderful King', 'The Wonderful King', 'A Wonderful King', 'Princess Down', 'The Princess Down', 'Princess Is Down', 'Get Down Moses', 'Go Down Moses', 'Let My People Go'],
  'Awareness': ['Awareness of NPC', 'Awareness of NPCs', 'Awareness of the NPC', 'NPC Awareness', 'Delete Bots Now', 'Delete the Bots Now', 'Delete Bots', 'Parietal Power', 'The Parietal Power', 'Element Wasser', 'Element Water', 'The Water Element'],
  'Torah & lineage': ['Apply Oldest Torah', 'Apply the Oldest Torah', 'The Oldest Torah', 'Oldest Torah', 'Body as Torah Scroll', 'The Body as Torah Scroll', 'Body as a Torah Scroll', 'My Body Is a Torah Scroll', 'Babylonian Talmudism', 'Babylonian Talmud', 'The Babylonian Talmud', 'Talmudism', 'King David Lineage in America', 'King David Lineage', 'The Lineage of King David', 'Davidic Lineage in America', 'Real Masonic Story', 'The Real Masonic Story', 'Masonic Story', 'Moral Story Theme', 'The Moral Story Theme', 'Moral of the Story'],
  'Prophecy': ['Forty One Months', 'Forty Two Months', 'Forty Two Months of Tribulation', 'Three and a Half Years', 'Twelve Hundred Sixty Days', 'Time Times and Half a Time'],
  'Politics': ['King Trump My Idol', 'King Trump', 'Trump My Idol', 'Donald Trump My Idol'],
  'Trial & victim': ['The Hard Road Be Traveled','The Hard Road Traveled','Hard Road to Travel','The Narrow Road','The Narrow Way','Shes the Real Victim','She Is the Real Victim','The Real Victim','Innocent Victim','She Was the Victim'],
};
// "Being Christ Vessel" and variations across deities / entities
const VESSEL_ENTITIES = ['Christ','Jesus','Jesus Christ','God','the Lord','the Holy Spirit','Yahweh','the Messiah','the Most High','Michael','Gabriel','Metatron','Sophia','Lucifer','Satan','the Devil','the Antichrist','the Beast','Baphomet','Babalon','Shiva','Vishnu','Krishna','Kali','Brahma','the Buddha','Maitreya','Allah','the Mahdi','Osiris','Horus','Isis','Ra','Thoth','Zeus','Apollo','Dionysus','Odin','Loki','Marduk','Baal','Mithras','Quetzalcoatl','the Divine','the Spirit'];
const VESSEL_FORMS = ['Being {e} Vessel','Being the {e} Vessel','Being a {e} Vessel','{e} Vessel','The {e} Vessel','Vessel of {e}','The Vessel of {e}','Being the Vessel of {e}','Being a Vessel of {e}','Being a Vessel for {e}','Chosen Vessel of {e}','Being {e}s Vessel','Being {e} Temple','Being {e} Channel','Being {e} Host','Being {e} Instrument','Being {e} Avatar','Being {e} Incarnate'];
const vesselPhrases = () => VESSEL_ENTITIES.flatMap(e => VESSEL_FORMS.map(f =>
  f.replace('{e}', e).replace(/\b(the|a) the /gi, '$1 ')));
// short explanations shown next to obscure phrases (kept separate so they don't change totals)
export const NOTES = {
 "Decode NRWN QSR": "NRWN QSR is \"Nero Caesar\" in Hebrew letters (נרון קסר), which totals 666 — the classic reading of Revelation 13:18",
 "Decode NRWNQSR": "NRWN QSR is \"Nero Caesar\" in Hebrew letters (נרון קסר), which totals 666",
 "NRWN QSR": "\"Nero Caesar\" transliterated into Hebrew letters; totals 666 in Hebrew gematria",
 "נרון קסר": "\"Nero Caesar\" in Hebrew letters (Neron Qesar); totals 666",
 "נרו קסר": "\"Nero Caesar\" without the final N (Latin spelling); totals 616, the variant number in some early Revelation manuscripts",
 "Neron Kaisar": "Greek form of \"Nero Caesar\"; its Hebrew spelling totals 666",
 "Neron Qesar": "Hebrew form of \"Nero Caesar\"; totals 666",
 "Nero Caesar": "Roman emperor (54–68 AD); his name in Hebrew letters totals 666",
 "Nero Caesar Six Six Six": "Nero Caesar in Hebrew letters totals 666 (Revelation 13:18)",
 "Dracone Bona Dividebant": "Latin: \"they were dividing the goods with the dragon\"",
 "In Hoc Signo Vinces": "Latin: \"In this sign you will conquer\" — Constantine's vision of the cross, 312 AD",
 "Jeppesen Terminal": "Main terminal of Denver International Airport, known for conspiracy lore about its murals",
 "The Jeppesen Terminal": "Main terminal of Denver International Airport",
 "I Am Project Monarch": "Project Monarch: alleged CIA mind-control program — conspiracy lore, not documented",
 "Project Monarch Survivor": "Project Monarch: alleged CIA mind-control program — conspiracy lore",
 "Akhenaten Dead Forever": "Akhenaten: Egyptian pharaoh (c. 1353–1336 BC) who imposed worship of the sun disk Aten",
 "Element Wasser": "Wasser is German for \"water\"",
 "Parietal Power": "Parietal lobe: brain region for sensation and spatial awareness",
 "Forty One Months": "Revelation 13:5 gives the beast forty-two months",
 "Forty Two Months": "Revelation 13:5 — the beast's reign; equals 1,260 days or 3½ years",
 "Twelve Hundred Sixty Days": "Revelation 11:3 and 12:6 — equals forty-two months",
 "Time Times and Half a Time": "Daniel 7:25 and Revelation 12:14 — read as 3½ years",
 "One Five Three": "153: the number of fish caught in John 21:11",
 "One Five Three Fish": "John 21:11 — the disciples catch 153 fish",
 "One Hundred Fifty Three Fish": "John 21:11 — the disciples catch 153 fish",
 "Gad Zooks or Gadzooks": "Gadzooks: old mild oath, probably from \"God's hooks\" (the nails of the cross)",
 "Gadzooks": "Old mild oath, probably from \"God's hooks\" (the nails of the cross)",
 "Pissflaps Dawn": "Pissflaps: British slang, crude",
 "Babylonian Talmud": "Main compilation of Jewish law and commentary, completed c. 500 AD",
 "Babylonian Talmudism": "Talmud: main compilation of Jewish law; \"Talmudism\" is often used as a pejorative",
 "Get Down Moses": "Echoes \"Go Down Moses\", the spiritual about the Exodus",
 "Go Down Moses": "African-American spiritual about the Exodus (Exodus 5:1)",
 "Let My People Go": "Exodus 5:1 — Moses' demand to Pharaoh",
 "Awareness of NPC": "NPC: \"non-player character\", slang for people seen as acting without independent thought",
 "Pinkie Pie Le Dijo Smile": "Spanish/English mix: \"Pinkie Pie told her Smile\" (My Little Pony)"
};
export const noteFor = p => NOTES[Object.keys(NOTES).find(k => k.toLowerCase() === p.trim().toLowerCase())] || '';
// she -> he / they variants for the personal phrases
const pronounVariants = p => /\bshes?\b/i.test(p) ? [p, p.replace(/\bShes\b/g,'Hes').replace(/\bShe\b/g,'He'), p.replace(/\bShes\b/g,'Theyre').replace(/\bShe Is\b/g,'They Are').replace(/\bShe\b/g,'They').replace(/\bThey Gets\b/g,'They Get').replace(/\bThey Was\b/g,'They Were')] : [p];
// every title with and without a leading "the"
const withThe = list => [...new Set(list.flatMap(e => /^the /i.test(e) ? [e, e.slice(4)] : [e, 'the '+e]))];

// Every built-in list, each tagged with the checkbox ("opt") that enables it.
export function allEntries(){
  const out = [], add = (p, list, opt) => out.push([p, list, opt]);
  for (const k of ['holy','unholy','nations']) LISTS[k].forEach(p => add(p, k, k));
  withThe(EPITHETS).forEach(e => { add(e, 'holy title', 'names'); HOLY_NAMES.forEach(h => { if (!e.startsWith(h)) add(h+' '+e, 'name combo', 'names'); }); });
  withThe(UNHOLY_EPITHETS).forEach(e => { add(e, 'unholy title', 'unames'); UNHOLY_NAMES.forEach(h => add(h+' '+e, 'unholy combo', 'unames')); });
  JUDGE_PHRASES.forEach(p => add(p, 'judgment', 'judge'));
  JUDGES.forEach(j => JUDGE_VERBS.forEach(v => JUDGED.forEach(d => add(j+' '+v+' '+d, 'judgment', 'judge'))));
  vesselPhrases().forEach(p => add(p, 'Vessel', 'phrases'));
  for (const [cat, ps] of Object.entries(PHRASES)) ps.flatMap(pronounVariants).forEach(p => add(p, cat, 'phrases'));
  for (const [cat, ps] of Object.entries(RESEARCH)) ps.forEach(p => add(p, cat, 'x:' + cat.split(':')[0]));
  TITLES.forEach(t => LISTS.nations.forEach(n => add(t+' '+n, 'combo', 'combos')));
  return out;
}
